config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    
    validates :title, 
        presence: true, 
        length: {minimum: 6, maximum: 100}
    
    validates :description, 
        presence: true, 
        length: {minimum: 10, maximum: 300}
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase}
    has_many :articles
    has_secure_password

    validates :username, 
        presence: true, 
        uniqueness: {case_sensitive: false}, 
        length: {minimum: 3, maximum: 25}

    VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :email, 
        presence: true, 
        uniqueness: {case_sensitive: false}, 
        length: {maximum: 105},
        format: { with: VALID_EMAIL_REGEX}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    before_action :set_article, only: [:show, :edit, :update, :destroy]

    def index
        @articles =  Article.all
    end

    def show
    end

    def new
        @article = Article.new
    end

    def edit
    end

    def create
        @article = Article.new(article_params)
        @article.user = User.first
        if @article.save
            flash[:notice] = "Article created."
            redirect_to @article
        else
            render 'new'
        end
    end

    def update
        if @article.update(article_params)
            flash[:notice] = "Article updated"
            redirect_to @article
        else
            render 'edit'
        end
    end

    def destroy
        @article.destroy
        redirect_to @article
    end

    private
    def set_article
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :description)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
    end

    def about
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            flash[:notice] = "Welcome to the alpha blog, #{@user.username}. You have successfully signed up"
            redirect_to articles_path
        else
            render 'new'
        end
    end

    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
        @articles = @user.articles
    end


    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:notice] = "Account Updated"
            redirect_to @user
        else
            render 'edit'
        end
    end


    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user, options = {size: 80})
        email_address= user.email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        size = options[:size]
        gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container">
    <% @articles.each do |article| %>
        <div class="row justify-content-md-center">
            <div class="col-8 mt-4">
                <div class="card text-center shadow mb-5 bg-white rounded">
                    <p class="card-header font-italic">
                      <% if article.user %>
                        by <%= link_to article.user.username, user_path(article.user) %> </p>
                      <% end %>
                    <div class="card-body">
                        <h5 class="card-title"> <%= link_to article.title, article_path(article), class:"text-success" %> </h5>
                        <p class="card-text"><%= truncate(article.description, length: 100) %></p>
                        <%= link_to 'View', article_path(article), class:"btn btn-outline-success" %>
                        <%= link_to 'Edit', edit_article_path(article), class:"btn btn-outline-warning" %>
                        <%= link_to 'Delete', article_path(article), class:"btn btn-outline-danger", method: :delete, data: {confirm: 'Are you sure?'}  %>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-10">
            <%= render 'shared/errors', obj: @article %>
            <%= form_with(model: @article, class:"shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
                <div class="form-group row">
                    <%= f.label :title, class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.text_field :title, placeholder: "Title of Article", class: "form-control shadow rounded" %>
                    </div>
                </div>

                <div class="form-group row">
                    <%= f.label :description, class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.text_area :description, rows: 10, placeholder: "Description of article", class: "form-control shadow rounded" %>
                    </div>
                </div>

                <div class="form-group row justify-content-center">
                    <%= f.submit class: "btn btn-outline-light btn-lg" %>
                </div>
            <% end %>
            <div class="row justify-content-center">
                <%= link_to 'Return to Articles', articles_path, class: "text-info" %>
            </div>
        </div>
    </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit Article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing All Articles</h1>


<%= render 'article' %>


<p>
    <%= link_to 'Create New Article', new_article_path %>
</p>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create New Article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center mt-4"><%= @article.title %></h2>


<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
            <div class="card text-center shadow mb-5 bg-white rounded">
                <div class="card-header font-italic"> 
                  <% if @article.user %>
                    by <%= @article.user.username %>
                    <%= link_to gravatar_for(@article.user), user_path(@article.user) %> 
                  <% end %>
                </div>
                <div class="card-body">
                    <div class="card-text text-left"><%= simple_format(@article.description) %></div>
                    <%= link_to 'Edit', edit_article_path(@article), class:"btn btn-outline-warning" %>
                    <%= link_to 'Delete', article_path(@article), class:"btn btn-outline-danger", method: :delete, data: {confirm: 'Are you sure?'}  %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
    <div class="container text-center">
        <small>Copyright &copy Michael Newman</small>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, message| %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= message %>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<div class="container-fluid">
  
  <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id:"logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
        <%= link_to "Bloggers", users_path, class:"nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
          Articles
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Create new Article", new_article_path, class: "dropdown-item" %>
          <%= link_to "View Articles", articles_path, class: "dropdown-item" %>
          <li><hr class="dropdown-divider"></li>
          <li><a class="dropdown-item" href="#">Something else here</a></li>
        </ul>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="d-flex">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>This is the about page!!!</p>

<%= link_to 'Articles', articles_path %> |
<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<div id="#home-container">
    <h1>This is the home page</h1>
    <div class="bg-dark text-center" style="height:400px; margin: 2rem; width: 80%"}>
        <p style="color:#FFFFFF">Alpha Blog</p>
        <%= link_to "Sign up!", signup_path, class: "btn btn-success btn-lg" %>
    </div>

    <%= link_to 'Articles', articles_path %> |
    <%= link_to 'About', about_path %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any?  %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
        <ul>
            <% obj.errors.full_messages.each do |message| %>
                <li>
                    <%= message %>
                </li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-10">
            <%= render 'shared/errors', obj: @user %>
            <%= form_with(model: @user, class:"shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
                <div class="form-group row">
                    <%= f.label :username, class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.text_field :username, placeholder: "Enter a username", class: "form-control shadow rounded" %>
                    </div>
                </div>

                <div class="form-group row">
                    <%= f.label :email, class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.email_field :email, placeholder: "Enter your email", class: "form-control shadow rounded" %>
                    </div>
                </div>

                <div class="form-group row">
                    <%= f.label :password, class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.password_field :password, placeholder: "Choose a password", class: "form-control shadow rounded" %>
                    </div>
                </div>

                <div class="form-group row justify-content-center">
                    <%= f.submit(@user.new_record? ? "Sign up" : "Update Account", class: "btn btn-outline-light btn-lg") %>
                </div>
            <% end %>
            <div class="row justify-content-center">
                <%= link_to 'Return to Articles', articles_path, class: "text-info" %>
            </div>
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your Profile</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpha Bloggers</h1>

<div class="container">
    <% @users.each do |user| %>
        <div class="row justify-content-md-center">
            <div class="col-8 mt-4">
                <div class="card text-center shadow mb-5 bg-white rounded">
                    <p class="card-header font-italic"> <%= link_to user.username, user %> </p>
                    <div class="card-body">
                        <%= link_to gravatar_for(user, size: 150), user_path(user) %>  
                        <p class="card-text"><%= pluralize(user.articles.count, "article") %> </p>
                        <%= link_to 'View Profile', user, class:"btn btn-outline-success" %>
                        <%= link_to 'Edit Profile', edit_user_path(user), class:"btn btn-outline-info" %>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign Up for Alpha Blog</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s Profile</h1>

<%= gravatar_for @user, size: 200 %>

<div class="text-center mt-4">
    <%= link_to "Edit Your Profile", edit_user_path(@user), class:"btn btn-outline-info" %>
</div>

<h3 class="text-center mt-4">Articles</h3>

<%= render 'articles/article' %>